urls.py
from django.views.generic.base import RedirectView
from django.urls import path, reverse_lazy
from . import views

app_name = 'prosdib'

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('prosdib:project-list'))),
    path('project/', RedirectView.as_view(url=reverse_lazy('prosdib:project-list'))),
    path('project/create/', views.ProjectCreate.as_view(), name='project-create'),
    path('project/<int:pk>/update/', views.ProjectUpdate.as_view(), name='project-update'),
    path('project/<int:pk>/detail/', views.ProjectDetail.as_view(), name='project-detail'),
    path('project/<int:pk>/delete/', views.ProjectSoftDelete.as_view(), name='project-delete'),
    path('project/list/', views.ProjectList.as_view(), name='project-list'),
    path('project/<int:projectpk>/projectnote/create', views.ProjectProjectNoteCreate.as_view(), name='projectprojectnote-create'),
    path('technician/', RedirectView.as_view(url=reverse_lazy('prosdib:technician-list'))),
    path('technician/create/', views.TechnicianCreate.as_view(), name='technician-create'),
    path('technician/<int:pk>/update/', views.TechnicianUpdate.as_view(), name='technician-update'),
    path('technician/<int:pk>/detail/', views.TechnicianDetail.as_view(), name='technician-detail'),
    path('technician/<int:pk>/delete/', views.TechnicianDelete.as_view(), name='technician-delete'),
    path('technician/list/', views.TechnicianList.as_view(), name='technician-list'),
    path('technician/<int:pk>/close/', views.TechnicianClose.as_view(), name="technician-close"),

]

models.py
from django.db import models
from django.conf import settings
from datetime import datetime
from django.apps import apps
from libtekin.models import Item, Location
from django.contrib.auth import get_user_model
from django.db.models import Count, OuterRef, Q, Subquery
from django.utils import timezone

def get_default_status():
    try:
        return Status.objects.filter(is_default=True).first().pk
    except AttributeError:
        return None

class Status(models.Model):
    name = models.CharField(
        'name',
        max_length=50,
        blank=True,
        help_text='The name of the technician'
    )
    list_position = models.IntegerField(
        'list position',
        default = 10000,
        help_text = 'The position of this status in a list, not sorted by other fields'
    )
    is_active = models.BooleanField(
        'is active',
        default=True,
        help_text='If this status means the project is active '
    )
    is_default = models.BooleanField(
        'default',
        default=False,
        help_text='If this status is the default for new projects.  Only one should be chosen'
    )

    def __str__(self):
        return f"{self.name}"

    class Meta:
        ordering=('list_position', 'name',)


class Technician(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='user',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='prosdib_technician',
        help_text='The user account associated with this technician'
    )
    name = models.CharField(
        'name',
        max_length=50,
        blank=True,
        help_text='The name of the technician'
    )
    is_current = models.BooleanField(
        'current',
        default=True,
        help_text='If this technician is current (should receive emails from projects, etc)'
    )

    def __str__(self):
        return f"{self.name}"

    @classmethod
    def user_is_tech(cls, user):
        return user in [ technician.user for technician in Technician.objects.all() ]

class ProjectManager(models.Manager):

    def get_queryset(self):
        
        return super().get_queryset(). \
            annotate(latest_update_when=Subquery(ProjectNote.objects.filter(project=OuterRef('pk')).filter(is_current=True).order_by('-when').values('when')[:1])). \
            annotate(qty_current_notes=Count('projectnote', filter=Q(projectnote__is_current=True))). \
            order_by('latest_update_when')

class Project(models.Model):
    PRIORITY_CHOICES = (
            (1, '1) Solve a Safety Hazard or Work Stoppage'),
            (2, '2) Fix a Major Problem or Implement a Major Improvement'),
            (3, '3) Fix a Highly Important Issue or Implement an Important Solution'),
            (4, '4) Fix a Moderately Important Issue or Implement a Moderately Importent Solution'),
            (5, '5) Fix a Minor Issue or implement a minor improvement')
    )

    title = models.CharField(
        'title',
        max_length=75,
        help_text='A short description of the project',
    )
    description = models.TextField(
        'description',
        blank=True,
        help_text='Details about the project'
    )
    priority = models.IntegerField(
        'priority',
        choices=PRIORITY_CHOICES,
        default=4,
        help_text='The priority, on a scale of 1 to 5, where 1 is the highest priority'
    )
    begin = models.DateTimeField(
        default=timezone.now,
        help_text='The date and time the project was submitted'
    )
    technician = models.ForeignKey(
        Technician,
        verbose_name='technician',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='project_responsibility',
        help_text='The technician primarily responsible for executing this project'
    )
    created_by = models.ForeignKey(
        Technician,
        verbose_name='created by',
        null=True,
        on_delete=models.SET_NULL,
        related_name='project_created',
        help_text='The technician who created this project'
    )
    status = models.ForeignKey(
        Status,
        verbose_name = 'status',
        on_delete = models.SET_NULL,
        null=True,
        default = get_default_status,
        help_text = 'The status of this project'
    )
    recipient_emails = models.TextField(
        'recipient emails',
        blank=True,
        help_text='The comma-separated list of emails of those who should get updates on this project.  By default, emails are sent for changes in notes and resolution status'
    )

    def __str__(self):
        return self.title

    def user_is_editor(self, user):
        return user == self.created_by or user.has_perm('prosdib.change_project')

    def get_current_notes(self):
        current_notes=[]

        for note in self.projectnote_set.filter(is_current=True):
            current_notes.append('{}: {}'.format(note.when.strftime('%Y-%m-%d'), note.maintext))

        return current_notes

    def get_time_spent(self):
        time_spent = 0
        for note in self.projectnote_set.filter(time_spent__gt=0):
            time_spent = time_spent + note.time_spent

        return time_spent

    objects = ProjectManager()

    class Meta:
        ordering=['status', 'priority']


class ProjectNote(models.Model):

    project=models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        help_text='The project to which this note applies',
    )
    maintext = models.CharField(
        'text',
        blank=True,
        max_length=255,
        help_text='The text of the note'
    )
    details = models.TextField(
        'details',
        blank=True,
        help_text='The details of the note if the main text is not sufficient'
    )
    submitted_by = models.ForeignKey(
        Technician,
        verbose_name='submitted by',
        null=True,
        on_delete=models.SET_NULL,
        help_text='The technician who submitted this note'
    )
    when = models.DateTimeField(
        'when',
        default=datetime.now,
        help_text='The date that the note was submitted'
    )
    time_spent = models.DecimalField(
        'time spent',
        default=0,
        decimal_places=2,
        max_digits=6,
        help_text='The amount of time to be added to the project as per this note.  Use decimal notation (ex 1.25, not 1:15)'
    )
    is_current = models.BooleanField(
        'is current status',
        default=False,
        help_text='If this note is diplayed by default in the project detail view.  If not, it will be displayed when "Show All" is selected'
    )

    class Meta:
        ordering = ['-when',]

    def __str__(self):
        return f'{self.when.date().isoformat()}: {self.maintext}' if self.when else self.maintext

class History(models.Model):

    when = models.DateTimeField(
        'when',
        auto_now_add=True,
        help_text='The date this change was made'
    )
    modelname = models.CharField(
        'model',
        max_length=50,
        help_text='The model to which this change applies'
    )
    objectid = models.BigIntegerField(
        'object id',
        null=True,
        blank=True,
        help_text='The id of the record that was changed'
    )
    fieldname = models.CharField(
        'field',
        max_length=50,
        help_text='The that was changed',
    )
    old_value = models.TextField(
        'old value',
        blank=True,
        null=True,
        help_text='The value of the field before the change'
    )
    new_value = models.TextField(
        'new value',
        blank=True,
        help_text='The value of the field after the change'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name='prosdib_history',
        null=True,
        help_text='The user who made this change'
    )

    class Meta:
        ordering = ('-when', 'modelname', 'objectid')

    def __str__(self):

        new_value_trunc = self.new_value[:17:]+'...' if len(self.new_value) > 20 else self.new_value

        try:
            model = apps.get_model('prosdib', self.modelname)
            object = model.objects.get(pk=self.objectid)
            return f'{self.when.strftime("%Y-%m-%d")}: {self.modelname}: [{object}] [{self.fieldname}] changed to "{new_value_trunc}"'

        except Exception as e:
            print (e)

        return f'{"mdy".format(self.when.strftime("%Y-%m-%d"))}: {self.modelname}: {self.objectid} [{self.fieldname}] changed to "{new_value_trunc}"'

templates/prosdib/_base.html
{% load static %}
{% load touglates_tags %}
<!DOCTYPE html>
<html lang='en'>
<head>
<title>Project Display Board</title>
<script src="{% static 'touglates/touglates.js' %}"></script>
<link rel="stylesheet" href="{% static 'prosdib/prosdib.css' %}">
{% project_include_file 'main_css' as cssfile %}
{% if cssfile %}<link rel="stylesheet" href="{% static cssfile %}">{% endif %}
</head>
<body>
  {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% block menu %}
{% project_include_file 'main_menu' as includefile %}
{% if includefile %}
  {% include includefile %}
{% endif %}
{% endblock %}
{% block content %}{% endblock %}
{% block bottomscript %}{% endblock %}
</body>
</html>

templates/prosdib/_detail_field.html
<div class="field-wrapper">
  <div class="control">
    <div class="label">
      {{ label }}
    </div>
    <div class="field">
      {{ field }}
    </div>
  </div>
</div>

templates/prosdib/_form.html
{% extends './_base.html' %}
{% load static %}
{% block content %}
{% endblock %}
{% block bottomscript %}
<script src="{% static 'touglates/touglates.js' %}"></script>
{% endblock %}

templates/prosdib/_form_button.html
<div class="field-wrapper">
  <div class="control">
    <div class="label">
      {{ label }}
    </div>
    <div class="field">
      {{ button }}
    </div>
  </div>
  <div class="help_text">
    {{ help_text}}
  </div>
</div>

templates/prosdib/_form_field.html
<div class="field-wrapper">
  {% if field.errors %}
    <div class="errors">
      {{ field.errors }}
    </div>
  {% endif %}
  <div class="control">
    <div class="label">
      {% if label_tag %}
        {{ label_tag }}
      {% else %}
        {{ field.label_tag }}
      {% endif %}
    </div>
    <div class="field">
      {{ field }} {{ extra }}
    </div>
  </div>
  <div class="help_text">
    {% if help_text %}
      {{ help_text }}
    {% else %}
     {{ field.help_text}}
    {% endif %}
  </div>
</div>

templates/prosdib/_list_head.html
<div class="field">
  {{ field }}
</div>

templates/prosdib/project_confirm_delete.html
{% extends './_base.html' %}
{% block content %}
  {% include './project_detail_include.html' %}
<form method="POST">
{% csrf_token %}
<div>
Delete? {{ form.is_deleted }}
<button type="submit">Confirm</button>
</div>
{% endblock %}

templates/prosdib/project_detail.html
{% extends './_base.html' %}
{% load prosdib_perm_checks %}
{% block content %}

  {% include './project_detail_include.html' %}

  <div class="menu-bottom">
    {% user_is_editor object user as editor %}
    {% if editor %}
      <div class="menu-item">
        <a id="a_addnote" href="{% url 'prosdib:projectprojectnote-create' object.pk %}">Add Note</a>
      </div>
    {% endif %}
    {% if perms.prosdib.change_project %}
      <div class="menu-item">
        <a href="{% url 'prosdib:project-update' object.pk %}">Edit</a>
      </div>
    {% endif %}
  </div>
  <script>
    document.getElementById('a_addnote').addEventListener('click', function(e) {
      e.preventDefault()
      window.open(e.target.href)
    });
  </script>
{% endblock %}

templates/prosdib/project_detail_include.html
{% load prosdib_perm_checks %}
  <h2>{{ object }}</h2>

  <div class="detail">
    {% include './_detail_field.html' with label=project_labels.title field=object.title %}
    {% include './_detail_field.html' with label=project_labels.description field=object.description %}
    {% include './_detail_field.html' with label=project_labels.priority field=object.get_priority_display %}
    {% include './_detail_field.html' with label=project_labels.technician field=object.technician %}
    {% include './_detail_field.html' with label=project_labels.created_by field=object.created_by %}
    {% include './_detail_field.html' with label=project_labels.begin field=object.begin %}
    {% include './_detail_field.html' with label=project_labels.status field=object.status %}
    {% include './_detail_field.html' with label='Total time spent' field=object.get_time_spent %}

    {% if not hide_notes %}
    <h3>Notes</h3><span id="div_projectNotesShowing">Showing All </span><a href="#" id="a_toggleCurrent">Show Current</a>
    {% for projectnote in object.projectnote_set.all %}
      <div class="relatedset relatedprojectnote{% if projectnote.is_current %} current{% endif %}" id="div_projectnote-{{ forloop.counter0 }}">
        <div class="fieldWrapper">
          <div class="control">
            <div class="label">
              Note:
            </div>
            <div class="field">
              {{ projectnote }}
            </div>
          </div>
          {% if projectnote.details %}
            <div class="control">
              <div class="label">
                &nbsp;Details:
              </div>
              <div class="field">
                &nbsp;{{ projectnote.details }}
              </div>
            </div>
          {% endif %}
        </div>
      </div>
    {% endfor %}
    {% endif %}
  </div>

  <script>
    function refreshDiv(fields, model) {
      var emptydiv = document.getElementById('div_' + model + '-empty')
      var newdiv = emptydiv.cloneNode(true)
      var allRelatednoteDivs = document.getElementsByClassName('relatednote')
      newdiv.id = 'div_' + model + '-' + allRelatednoteDivs.length
      keys = Object.keys(fields)
      console.log('keys:')
      console.log(keys)
      for(key of keys){
        console.log("span[data-field='" + key + "']")
        console.log(fields[key])
        newdiv.querySelector("span[data-field='" + key + "']").innerText=fields[key]
      }
      newdiv.style.display="block"
      emptydiv.parentNode.insertBefore(newdiv, emptydiv)
    }
  </script> 
  <script>
    function toggleCurrentNotes() {
      var projectNotes=document.getElementsByClassName('relatedprojectnote')
      var projectNotesShowing = document.getElementById('div_projectNotesShowing')
      var toggleCurrent = document.getElementById('a_toggleCurrent')
      if(toggleCurrent.textContent=='Show All '){
        for(projectNote of projectNotes) {
          if(!(projectNote.classList.contains('current'))){
            projectNote.classList.remove('hidden')
          }
        }
        toggleCurrent.textContent='Show Current '
        projectNotesShowing.textContent='Showing All '
      } else {
        for(projectNote of projectNotes) {
          if(!(projectNote.classList.contains('current'))){
            console.log('adding hidden')
            projectNote.classList.add('hidden')
          }
        }
        toggleCurrent.textContent='Show All '
        projectNotesShowing.textContent='Showing Current Status'
      }
    }
    toggleCurrentNotes()
    document.getElementById('a_toggleCurrent').addEventListener('click', function(e) {
      e.preventDefault()
      toggleCurrentNotes()
    });
  </script>

templates/prosdib/project_form.html
{% extends './_form.html' %}
{% load static %}
{% load prosdib_perm_checks %}
{% block content %}
  <h2>{{ object }}</h2>
  {{ form.errors }}
  <form method="POST">
    <div class="form">
      {% csrf_token %}
      {% for field in form.hidden_fields %}
        {{ field }}
      {% endfor %}

      <div id="div_title">
        {% include './_form_field.html' with field=form.title %}
      </div>
      <div id="div_description">
        {% include './_form_field.html' with field=form.description %}
      </div>
      <div id="div_begin">
        {% include './_form_field.html' with field=form.begin %}
      </div>
      <div id="div_priority">
        {% include './_form_field.html' with field=form.priority %}
      </div>
      {% if perms.prosdib.change_project %}
        <div id="div_technician">
          {% include './_form_field.html' with field=form.technician %}
        </div>
        <div id="div_status">
          {% include './_form_field.html' with field=form.status %}
        </div>
        <div id="div_recipient_emails">
          {% include './_form_field.html' with field=form.recipient_emails %}
        </div>
        <div id="div_send_mail">
          {% include './_form_field.html' with field='<input type="checkbox" name="send_mail">' label_tag="Send Emails" help_text="Send emails for this update" %}
        </div>
      {% endif %}

      {% include './_form_button.html' with label="Submit Form" button='<button type="submit">Submit</button>' %}

      <h3>Notes</h3>

      {{ projectnotes.management_form }}
      {% for projectnoteform in projectnotes.forms %}
        {% if projectnoteform.id.value > 0 %}
          <div id="div_projectnoteform_{{ projectnoteform.id.value }}" class="projectnoteformsetform"  >
            {% for hiddenfield in projectnoteform.hidden_fields %}
              {{ hiddenfield }}
            {% endfor %}
            {% include './_form_field.html' with field=projectnoteform.when %}
            {% include './_form_field.html' with field=projectnoteform.maintext %}
            {% include './_form_field.html' with field=projectnoteform.is_current %}
            {% include './_form_field.html' with field=projectnoteform.details %}
            {% include './_form_field.html' with field=projectnoteform.time_spent %}
            {% include './_form_field.html' with field=projectnoteform.DELETE %}
          </div>
        {% else %}
          <div class="projectnoteformsetform projectnotenewform" >
            {% for hiddenfield in projectnoteform.hidden_fields %}
              {{ hiddenfield }}
            {% endfor %}

            {% include './_form_field.html' with field=projectnoteform.when %}
            {% include './_form_field.html' with field=projectnoteform.maintext %}
            {% include './_form_field.html' with field=projectnoteform.is_current %}
            {% include './_form_field.html' with field=projectnoteform.details %}
            {% include './_form_field.html' with field=projectnoteform.time_spent %}
            {% include './_form_field.html' with field=projectnoteform.DELETE %}
          </div>
        {% endif %}
      {% endfor %}
      <table>
        <tr>
          <th>
            <button type="button" id="button_addprojectnote">Add</button>
          </th>
          <th>
            Date
          </th>
          <th>
            Text
          </th>
          <th>
            Time Spent
          </th>
          <th>
            Is Current
          </th>
        </tr>
        {% for projectnote in object.projectnote_set.all %}
          <tr id="tr_projectnote_{{ projectnote.id }}">
            <td>
              <button type="button" id="button_editprojectnote_{{ projectnote.id }}" data-formid="div_projectnoteform_{{ projectnote.id }}" data-displayid="tr_projectnote_{{ projectnote.id }}" class="projectnote_edit_button">edit</button>
            </td>
            <td>
              {{ projectnote.when }}
            </td>
            <td>
              {{ projectnote.maintext }}
            </td>
            <td>
              {{ projectnote.details }}
            </td>
            <td>
              {{ projectnote.time_spent }}
            </td>
            <td>
              <input type="checkbox" id="input_proxy_is_current_{{ projectnote.id }}" class="is_current_proxy"{% if projectnote.is_current %} checked="CHECKED"{% endif %} data-formid="div_projectnoteform_{{ projectnote.id }}">
            </td>
          </tr>
        {% endfor %}
      </table>
      {% include './_form_button.html' with label="Submit Form" button='<button type="submit">Submit</button>' %}

    </div>

  </form>

{% endblock %}
{% block bottomscript %}
  {{ block.super }}
  <script>
    addRelatedPopupButton( 'id_technician', 'Technician', '{% url "prosdib:technician-create" %}')
  function getControlIdsForPopups(modelName) {
    controlIds = {
      'Technician': ['id_technician']
    }
    return( controlIds[modelName])
  }
  </script>

  <script>
    function addAddNotePopupEvent() {
      aAddNote = document.getElementById('a_addnote')
      if(typeof(aAddNote) != 'undefined' && aAddNote != null){
        document.getElementById('a_addnote').addEventListener('click', function(e) {
          e.preventDefault()
          window.open(e.target.href)
        });
      }
    }
    addAddNotePopupEvent()
    function refreshDiv(fields, model) {
      var emptydiv = document.getElementById('div_' + model + '-empty')
      var newdiv = emptydiv.cloneNode(true)
      var allProjectnoteDivs = document.getElementsByClassName('relatedprojectnote')
      newdiv.id = 'div_' + model + '-' + allProjectnoteDivs.length
      keys = Object.keys(fields)
      console.log('keys:')
      console.log(keys)
      for(key of keys){
        console.log("span[data-field='" + key + "']")
        console.log(fields[key])
        newdiv.querySelector("span[data-field='" + key + "']").innerText=fields[key]
      }
      newdiv.style.display="block"
      emptydiv.parentNode.insertBefore(newdiv, emptydiv)
    }
  </script>
  <script>
    function enableFormsetForm(formid, displayid) {
      let form = document.getElementById(formid)
      document.getElementById(formid).style.display="block"
      document.getElementById(displayid).style.display="none"
    }
    let projectnoteEditButtons = document.getElementsByClassName('projectnote_edit_button')
    for( projectnoteEditButton of projectnoteEditButtons){
      projectnoteEditButton.addEventListener('click', function(e){
        e.preventDefault()
        enableFormsetForm(e.target.dataset.formid, e.target.dataset.displayid)
      })
    }
    function enableAddFormsetForm(formclass) {
      let newforms = document.getElementsByClassName(formclass)
      if( newforms.length > 0) {
        let newform = newforms[0]
        newform.style.display="block"
        newform.classList.remove(formclass)
      } else {
        alert('please save before adding more')
      }
    }

    document.getElementById('button_addprojectnote').addEventListener('click', function(e){
      e.preventDefault()
      enableAddFormsetForm('projectnotenewform')
    })
    let projectnoteforms = document.getElementsByClassName("projectnoteformsetform")
    for( projectnoteform of projectnoteforms ){
      projectnoteform.style.display="none"
    }

  </script>

{% endblock %}

templates/prosdib/projectprojectnote_closer.html
{% extends './_base.html' %}
{% block content %}
<script>
if(window.opener) {
  window.opener.refreshDiv({'when':'{{ object.when }}', 'text':'{{ object.maintext }}'}, "projectnote")
  window.close()
}
</script>
{% endblock %}

templates/prosdib/technician_confirm_delete.html
{% extends './_base.html' %}
{% block content %}
{{ object }}
<form method="POST">
{% csrf_token %}
<div>
<button type="submit">Confirm Delete</button>
</div>
{% endblock %}

templates/prosdib/technician_detail_include.html
<h2>{{ object }}</h2>
<div class="detail">
  {% include './_detail_field.html' with label=mmodel_labels.user field=object.user %}
  {% include './_detail_field.html' with label=mmodel_labels.name field=object.name %}
  {% include './_detail_field.html' with label=mmodel_labels.is_active field=object.is_active %}

</div>

templates/prosdib/technician_form.html
{% extends './_form.html' %}
{% load static %}
{% load prosdib_perm_checks %}
{% block content %}
  <h2>{{ object }}</h2>
  {{ form.errors }}
  <form method="POST">
    <div class="form">
      {% csrf_token %}
      <input type="hidden" name='opener' id="input_opener">
      {% for field in form.hidden_fields %}
        {{ field }}
      {% endfor %}
      <div id="div_user">
        {% include './_form_field.html' with field=form.user %}
      </div>
      <div id="div_name">
        {% include './_form_field.html' with field=form.name %}
      </div>
      <div id="is_current">
        {% include './_form_field.html' with field=form.is_current %}
      </div>

      {% include './_form_button.html' with label="Submit Form" button='<button type="submit">Submit</button>' %}


    </div>

  </form>
  <script>
    if(window.opener) {
      document.getElementById('input_opener').value = window.opener.location.href
    }
  </script>

{% endblock %}
{% block bottomscript %}
  {{ block.super }}

{% endblock %}